import parse from 'html-react-parser';

// Strings object
const strings = {
    introH1: `Hello`,
    introTxt: ([userID]) => `Welcome to my website User${userID}.`,
    introLogoAlt: `Nick Sneed Logo`,
    mainIntro:
        `<p>
            Subject: <br>
            <span className="txt-l">
                Nick Sneed <br>
                Web Developer/Designer
            </span>
        </p>
        <p>
            Location: <br>
            O' Fallon, MO
        </p>
        <p>
            Specialization:<br>
            Creation of visually appealing and responsive websites.<br>
            Combination of design principles and technological expertise.<br>
            Development of user-centric online experiences.
        </p>`,
    socialTileInsta: 
        `<p>
            Objective: <br>
            Nostalgia induction via digital media platform 'Instagram'.
        </p>
        <p>
            Methodology: <br>
            Content analysis of archived visual data (photographs, videos).
        </p>
        <p>
            Data presentation: <br>
            Limited color spectrum mirroring aesthetic of Game Boy Camera.
        </p>`,
    socialTileInstaAlt: `Instagram`,
    socialTileInstaBt: `Shoot`,
    socialTileTumblr: 
        `<p>
            Objective:<br>
            Digital art portfolio.
            Visual representation of aesthetic preferences derived from video game media.
        </p>
        <p>
            Content:<br>
            Original artwork generated by BobRumbly (aka Nick Sneed).
        </p>
        <p>
            Data source: <br>
            Retro digital video games.
        </p>`,
    socialTileTumblrAlt: `Tumblr`,
    socialTileTumblrBt: `View`,
    socialTileGitHub: 
        `<p>
            Purpose:<br>
            Code repository.
            Documentation of software development activities.
            Exploration of emerging technologies.
        </p>
        <p>
            Content:<br>
            Source code.
            Project documentation.
            Experimental prototypes.
        </p>`,
    socialTileGitHubAlt: `GitHub`,
    socialTileGitHubBt: `Play`,
    footerInstaAlt: `Visit my Instagram`,
    footerTumblrAlt: `Visit my Tumblr`,
    footerGitHubAlt: `Visit my GitHub`,
    footerXAlt: `Visit my X/Twitter`,
    footerLinkedInAlt: `Visit my LinkedIn`,
    copy: ([year]) => `© 2024-${year} Nick Sneed`
}

// str function
const str = (k, isParse, v) => {
    const string = strings[k];
    const s = typeof string === 'function' ? string(v) : string;
    return isParse ? parse(s) : s;
}

export default str;